language:
  - "python"

python:
  -"3.6"

before_install:

virtualenv:
  - system-site-packages: false


install:
  - "pip3 install -requirements.txt"
  - "pip3 install coveralls"

script:
  - "pytest --cov"




